### ISSUE TITLE
LICENCE update

### ISSUE THREAD

**Issue by zshi-redhat** [Mellanox/ib-sriov-cni#34]
I noticed there was a branch called `licence`, any plan to merge the licence change to master branch?

**Comment by moshe010** [comment]
So it was already merged [1] but from some reason I can't delete the branch. 
I think I need to contact github support to delete it

[1] - https://github.com/Mellanox/ib-sriov-cni/blob/license/LICENSE

**Comment by zshi-redhat** [comment]
> So it was already merged [1] but from some reason I can't delete the branch.
> I think I need to contact github support to delete it
> 
> [1] - https://github.com/Mellanox/ib-sriov-cni/blob/license/LICENSE

Yes, it was there.
